### ISSUE TITLE
bicycle=use_sidepath indicates that cyclists should use not this way but the separate cycleway

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/conf#27]
When routing over road https://www.openstreetmap.org/way/221051138 and the roundabout next to it, I noticed the cycle routing was done over the road, not over the cycle path.
The ways have the tag bicycle=use_sidepath. This tag should indicate, that there is a different path for cyclists to use, so the cyclists should not be routed over this way.
I see however in your code, that use_sidepath implies access = true.

**Comment by gknisely** [comment]
Albert,

Thank you for reporting this issue.  I will apply the change and test it
out before pushing the change to our production servers.  I will let you
know when this is done.

Thanks.

  --Greg

**Comment by gknisely** [comment]
Albert,

We are still looking into this issue; however, the other issues that you
reported should be resolved.  I hope you can get a moment to verify them
and let us know if everything looks good.

Thank you for your time.

  --Greg.

**Comment by gknisely** [comment]
Other issues meaning the bicycle errors.
