### ISSUE TITLE
Problems with handling of oneway:bicycle=no

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/conf#28]
I have spotted a few errors in the handling of one-way for cyclists.

Road https://www.openstreetmap.org/way/48672084 with the tags cycleway=lane and oneway:bicycle=no, is not used in backward direction.
The same happens on road https://www.openstreetmap.org/way/244945480 with cycleway=cyclestreet and oneway:bicycle=no.
It appears to me, that oneway:bicycle is not checked in the code in edges.lua because neither line 616 nor line 618 sets kv["bike_backward"] to true and this condition is checked on line 622.

Roads https://www.openstreetmap.org/way/7053107 and https://www.openstreetmap.org/way/7053048 with the tags oneway=yes, cycleway=opposite are not used in forward direction. The OSM Wiki indicates that cycleway=opposite means 2-way cycling is possible on a one-way road.
This is likely because kv["bike_forward"] is set to false on line 651.

**Comment by gknisely** [comment]
Thanks again Albert.  When I review the previous issue, I will take a look
at these as well.  Also, thank you for providing specific ways.  I will add
these to our tests.

--Greg.

**Comment by AlbertJP** [comment]
The first road I mentioned, is of "type M1" on page https://www.openstreetmap.org/way/48672084, and is tagged correctly.
I have however, just changed highway=service into highway=residential as this tag opposed the wiki's guidelines. I do not know if that matters.

I just see I have been a bit unclear: with "not used", I meant the routing engine avoids the roads in that direction. It should be possible as cyclist, to traverse mentioned ways in both directions, right now only one direction is routeable.

**Comment by gknisely** [comment]
Albert,

These issues should be fixed.  I hope you can get a moment to verify them
and let us know if everything looks good.

Thanks again.

  --Greg.

**Comment by AlbertJP** [comment]
Thank you, it is fixed now.
