### ISSUE TITLE
Cycle route avoids barrier=bollard

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/conf#29]
Here is a bollard in a cycle path to prevent cars using the path. For cars it is a barrier, for cyclists (and pedestrians) not at all.
https://www.openstreetmap.org/node/1308362935

When routing from 52.06787, 5.10260 to 52.06807, 5.10241, it becomes apparent this bollard is avoided.

Objects like these on cycle paths are very common in my city. There are hundreds of them, overpass shows 379 but many are not mapped.

**Comment by gknisely** [comment]
I updated the vertices.lua.   This was a simple copy and paste bug.  This
will go out with the other updates for the issues that you reported.

  --Greg.

**Comment by gknisely** [comment]
Albert,

This issue should be fixed.

Thanks again.

  --Greg.

**Comment by AlbertJP** [comment]
Thank you, it is fixed now.
