### ISSUE TITLE
admin -> admin_dir

### ISSUE THREAD

**Issue by molind** [valhalla/conf#41]
Hello, just noticed that mjolnir/pbfadminbuilder requires admin.admin_dir + admin.db_name. But config contains just "admin" option.

**Comment by gknisely** [comment]
Thanks @molind I will take a look at this issue.

**Comment by kevinkreiser** [comment]
yeah `pbfgraphbuilder` changed to the simplified version but forgot to update `pbfadminbuilder`. appologies

**Comment by gknisely** [comment]
@molind you should be all set.  Thank you for reporting this issue.

--Greg.
