### ISSUE TITLE
Run meili and tyr simultaneously

### ISSUE THREAD

**Issue by ptpt** [valhalla/conf#54]
Unable to run both simultaneously since they conflict at the httpd port 8002.

A workaround here is to use two separate `valhalla.json`, with specifying different ports in `httpd.service.listen`, for tyr and meili respectively.

**Comment by kevinkreiser** [comment]
yeah at current this isnt a problem for us as we will be running them on separate machines. at some point (after some prime_server additions) we would be able to run them behind the same server and on different workers. when that happens this will be a moot issue. until then yeah have a different config is the quickest way around

**Comment by kevinkreiser** [comment]
we're working on adding the outputs of meili to the trace_* methods and will probably allow meili results from there as well.
